# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Netdata.Netdata
PackageVersion: 2.12.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{83002543-7FD0-40FD-836B-CC326C3ACF38}'
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- DisplayName: Netdata Agent
  ProductCode: '{83002543-7FD0-40FD-836B-CC326C3ACF38}'
  UpgradeCode: '{0D949B90-A54D-4AAE-9616-E15FBC410530}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Netdata'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/netdata/netdata/releases/download/v2.12.0/netdata-v2.12.0-x64.msi
  InstallerSha256: C18AD320AFBD695D7814214D0EF5FA13B1E423AF95D88A3A45C00F48DFB52CBC
ManifestType: installer
ManifestVersion: 1.12.0
