# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: swisstopo.GeoSuite
PackageVersion: 1.7.5542
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /exenoui /exenoupdates /qn /norestart
  SilentWithProgress: /exenoui /exenoupdates /qb /norestart
UpgradeBehavior: install
ProductCode: '{E7D68CA7-35B8-4480-84F1-D4AF3800C13F}'
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- DisplayName: GeoSuite
  Publisher: swisstopo
  DisplayVersion: 1.7.5542
  ProductCode: '{E7D68CA7-35B8-4480-84F1-D4AF3800C13F}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\swisstopo\GeoSuite'
Installers:
- Architecture: x86
  InstallerUrl: https://geosuite.swisstopo.ch/GeoSuite17_setup.exe
  InstallerSha256: 4EADB5CA86160F18561C6C779AF1B6F054EF6B61D999C3D347740D8506986D13
ManifestType: installer
ManifestVersion: 1.12.0
